### ISSUE TITLE
Release notes/ChangeLog

### ISSUE THREAD

**Issue by 0323pin** [igor-petruk/oatbar#9]
Updated the NetBSD package to 0 0.29 earlier today and added as commit message what I thought was relevant, https://mail-index.netbsd.org/pkgsrc-changes/2023/11/29/msg287839.html

I see 0.0.30 was just tagged, I'll bump our package when I have time but, I thought it would probably be nicer if release highlights would come from you.

What do you say?

**Comment by igor-petruk** [comment]
Hi,

I currently do not put much thought into releasing because each time it is
minor fixes and improvements. We could hold off updating versions for now,
finish the docs and then I can post the announcement in some Reddit and
Rust channels (where I am basically happy with its state and ready to
receive feedback). For now I kind of randomly change things around, but I
do have some TODOs in mind.

wdyt?

If I do a release, should I simply put it into the Github Release like
here: https://github.com/leftwm/leftwm/releases?

ср, 29 лист. 2023 р. о 17:15 pin ***@***.***> пише:

**Comment by 0323pin** [comment]
Fair enough, I understand that. Let's leave the highlights for when you do official releases. Anything against noticing major changes on our commit logs? I can always write, **"No ChangeLog provided"**

Yeah, I think the example from LeftWM is suitable.

**Comment by igor-petruk** [comment]
I will just do it less frequently from now on and I will publish the
changelog, so you don't have to worry about this. Thank you 🙏

**Comment by 0323pin** [comment]
> I will just do it less frequently from now on ...

You do whatever you want, it's your project. I maintain `oh-my-posh` for NetBSD and only this year he has released over 70 versions.

It's annoying but, I try to keep-up with it. Even though, it's impossible to catch every release. I tend to update it once a week.
